apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: energypredict-prod
resources:
  - namespace.yaml
  - ../../base
nameSuffix: -prod
replicas:
  - name: energypredict-api
    count: 1
images:
  - name: energypredictacr.azurecr.io/energypredict-api
    newTag: prod-latest
patches:
  - path: patch-deployment-rollout.yaml
  - path: patch-deployment-resources.yaml
  - path: patch-deployment-secretproviderclass.yaml
  - path: patch-configmap.yaml
  - path: patch-serviceaccount.yaml
  - path: patch-serviceaccount-training.yaml
  - path: patch-serviceaccount-data-processor.yaml
  - path: patch-secretproviderclass.yaml
  - path: patch-ingress.yaml
  - path: patch-hpa.yaml
