apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - serviceaccount-training.yaml
  - serviceaccount-data-processor.yaml
  - secretproviderclass.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - configmap.yaml
  - hpa.yaml
  - training-rbac.yaml
  - data-processor.yaml
  - training-job.yaml
  - drift-monitor-cronjob.yaml
  - servicemonitor.yaml
  - prometheus-rules.yaml
  - grafana-dashboard.yaml
