apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: energypredict-kv-secrets
spec:
  provider: azure
  secretObjects:
    - secretName: energypredict-secrets
      type: Opaque
      data:
        - objectName: database-url
          key: DATABASE_URL
        - objectName: jwt-secret-key
          key: JWT_SECRET_KEY
        - objectName: azure-storage-connection-string
          key: AZURE_STORAGE_CONNECTION_STRING
        - objectName: databricks-token
          key: DATABRICKS_TOKEN
  parameters:
    usePodIdentity: "false"
    clientID: "REPLACE_ME_CLIENT_ID"
    keyvaultName: "REPLACE_ME_KEYVAULT_NAME"
    tenantId: "REPLACE_ME_TENANT_ID"
    objects: |
      array:
        - |
          objectName: database-url
          objectType: secret
        - |
          objectName: jwt-secret-key
          objectType: secret
        - |
          objectName: azure-storage-connection-string
          objectType: secret
        - |
          objectName: databricks-token
          objectType: secret
