apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: energypredict-api
spec:
  rules:
    - host: api-dev.energypredict.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: energypredict-api
                port:
                  number: 80
