apiVersion: v1
kind: ConfigMap
metadata:
  name: energypredict-config
data:
  ENVIRONMENT: "dev"
  LOG_LEVEL: "DEBUG"
  MODEL_STAGE: "staging"
  MLFLOW_TRACKING_URI: "databricks"
  MLFLOW_REGISTRY_URI: "databricks-uc"
  K8S_NAMESPACE: "energypredict-dev"
  K8S_TRAINING_JOB_SERVICE_ACCOUNT: "energypredict-training-dev"
  K8S_CONFIG_MAP_NAME: "energypredict-config-dev"
  API_INTERNAL_BASE_URL: "http://energypredict-api-dev/api/v1"
